### ISSUE TITLE
Error Loading into CodeSandbox.io

### ISSUE THREAD

**Issue by aaronksaunders** [ionic-team/ionic-react-hooks#3]
<pre>
Error: Could not fetch dependencies, please try again in a couple seconds: Something
went wrong while packaging the dependency @ionic/react-hooks@0.0.5: ENOENT: 
no such file or directory, 
scandir '/tmp/2309092033/node_modules/@ionic/react-hooks/dist/esm'
</pre>

**Comment by mlynch** [comment]
Hey Aaron, closing as this seems like just a temporary issue on their end. Let us know if you're not able to get around it.

**Comment by aaronksaunders** [comment]
still exists

**Comment by AWolf81** [comment]
@aaronksaunders I'm getting the same message at Codesandbox.

After looking at https://unpkg.com/browse/@ionic/react-hooks@0.0.5/ it looks like there is no `dist/esm` folder and Codesandbox is looking for https://unpkg.com/@ionic/react-hooks@0.0.5/dist/esm/index.js.
So I think it's related to the published version on npm and it's probably no issue from Codesandbox.

As it's the destination that's specified in `main` key of `package.json`. @mlynch could you please have a look? 

Would be awesome to test `ionic/react-hooks` on Codesandbox.

**Comment by aaronksaunders** [comment]
@AWolf81 @mlynch - i might take a stab at submitting a PR, never have deployed a package to npm but there is always a first
